
package biz.ist.isi.wsdl;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-28T17:07:58.729+02:00
 * Generated source version: 3.1.11
 * 
 */
public final class IsiPartnerInterface_IsiPartnerPort_Client {

    private static final QName SERVICE_NAME = new QName("http://isi.ist.biz/wsdl", "isiPartnerService");

    private IsiPartnerInterface_IsiPartnerPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IsiPartnerService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IsiPartnerService ss = new IsiPartnerService(wsdlURL, SERVICE_NAME);
        IsiPartnerInterface port = ss.getIsiPartnerPort();  
        
        {
        System.out.println("Invoking isiPartnerPull...");
        biz.ist.isi.types.IsiPartnerPull _isiPartnerPull_isiPartnerPull = null;
        biz.ist.isi.types.IsiPartnerPullResponse _isiPartnerPull__return = port.isiPartnerPull(_isiPartnerPull_isiPartnerPull);
        System.out.println("isiPartnerPull.result=" + _isiPartnerPull__return);


        }
        {
        System.out.println("Invoking isiPartnerPush...");
        biz.ist.isi.types.IsiPartnerPush _isiPartnerPush_isiPartnerPush = null;
        biz.ist.isi.types.IsiPartnerPushResponse _isiPartnerPush__return = port.isiPartnerPush(_isiPartnerPush_isiPartnerPush);
        System.out.println("isiPartnerPush.result=" + _isiPartnerPush__return);


        }

        System.exit(0);
    }

}
